#!/bin/bash
#SBATCH --job-name="goog_mr"
#SBATCH --output="/home/gdmaher/output/singularity.%j.out"
#SBATCH --error="/home/gdmaher/output/singularity.%j.err"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=48:00:00

module load singularity

CONTAINER=/home/gdmaher/tf.img

CONFIG=./config/googlenet_train300k_clean_mr.yaml

cd /home/gdmaher

echo "Starting job with config ${CONFIG}"
singularity exec --bind /home/gdmaher/data:/media ${CONTAINER} ./run.sh ${CONFIG}
